### ISSUE TITLE
Euronews Live no longer works.

### ISSUE THREAD

**Issue by solbu** [Twilight0/plugin.video.euronews.com#3]
For a while now the Live stream have not been working.

**Comment by Twilight0** [comment]
Thanks for reporting, will check.

**Comment by Twilight0** [comment]
Fixed in 1.2.0. Default setting is auto pick language based on kodi's interface language, if another language is desired you can force it from addon's own setting.

**Comment by solbu** [comment]
Thank you. Just tested it, and it works. 
Had to pull and update the tulip module too, but now it works. :-)

**Comment by Twilight0** [comment]
To pull updates normally you have to have my zips repository installed.
